### ISSUE TITLE
simulate.nullmodel or commsimulator: attrition during simulation?

### ISSUE THREAD

**Issue by fmassol** [vegandevs/vegan#109]
Hi,

I am trying to simulate bipartite network with known degree sequences using commsimulator (or simulate.nullmodel, whatever works...). It looks like the function actually decreases the number of 1's in the matrix (see code below).

Any help in finding out whether this is a real bug of commsimulator or a mistake of mine will be greatly appreciated.
Cheers,

François

Here is the incriminated code:

```r
## function alpha: computes parameter necessary for adjusting the power law degree sequences

alpha<-function(s,beta,c,d){
	locfun<-function(x){
		((rep(1,s)%*%sapply(sapply(floor(x*(1:s)^(-(1/(beta-1)))),function(z) min(z,d)),function(y) max(y,1)))-c)
	}
	uniroot(f=locfun,interval = c(0,2*c))$root
}

## function powerlawdegreeseq: yields a sequence of non-increasing degrees such that the ensuing distribution follows a power law of parameter beta, following Chung et al. 2003

powerlawdegreeseq<-function(s,beta,c,d){
	a <- alpha(s,beta,c,d)
	sapply(sapply(floor(a*(1:s)^(-(1/(beta-1)))),function(z) min(z,d)),function(y) max(y,1))
}

## function generateZ: takes two power law degree sequences and make it a random bipartite network

generateZ<-function(sa,sp,betaa,betap,c){
	delta <- powerlawdegreeseq(sa,betaa,c,sp)
	d <- powerlawdegreeseq(sp,betap,c,sa)
	z <- r2dtable(1, delta, d)[[1]]
	simulate(nullmodel(z, "quasiswap"))
}

## the problem with commsimulator...
histogram(sapply(rep(40,1000),function(x) sum(generateZ(20,20,2.2,2.2,x))))
## compare with what is obtained from Patel's algorithm (not binary matrix)
histogram(sapply(rep(40,1000),function(x) sum(r2dtable(1, powerlawdegreeseq(20,2.2,x,20), powerlawdegreeseq(20,2.2,x,20))[[1]])))
```

**Comment by jarioksa** [comment]
`quasiswap` returns binary null models, `r2dtable` returns non-binary models. If you submit non-binary data to `quasiswap`,  they will be transformed to binary (0 or 1). The `quasiwap` null will retain the number of zero and non-zero values in the data, but not the sum of the values if some of them were originally >1. 

In your `generateZ` function, the two last lines are the culprits:
```R
z <- r2dtable(1, delta, d)[[1]]  ## generate quantitative data with entries >1
simulate(nullmodel(z, "quasiswap")) ## transform z to binary & simulate
```
You should either use quantitative null models or specify a binary input to `quasiswap`.

**Comment by fmassol** [comment]
OK, thanks a lot. I didn't look at the code of quasiswap, but definitely should have. 

Would it be possible to implement the actual method described by Miklos & Podani (which they alternatively dub quasiswap or sum of squares), i.e. generating a random binary matrix with fixed marginals by first generating a random quantitative matrix and then "smoothing out" values above 1 checkerboard-wise? Practically, this would mean allowing the use of the current quasiswap method bwith y just the specification of marginals (and not a sample binary matrix with the targeted marginals).

Again, thanks for your answer.

**Comment by jarioksa** [comment]
This is how we implement Quasiswap: We first generate random quantitative matrix and then perform those sum-of-squres reducing swaps until only zeros and ones remain. Your problem was that you first generated a quantitative `r2dtable` matrix with lower number of non-zero values than needed, and then used this as a pattern for Quasi-swap. Quasi-swap (as implemented in our `"quasiswap"` method) then finds the 0/1 pattern matching your `r2dtable` which already had a lower number of non-zero entries than originally desired. So the dropping in the number of ones happened in `r2dtable` before `quasiswap`.

It is possible to write your own function to call `quasiswap` directly. However, this needs some care: these are internal functions, and if used directly, the responsibility is on the user. For instance, binary matrix may not exist for some patterns of row and column totals. We do not check this: we use an existing matrix as the row/column total pattern, and then we know that at least one such matrix exists. You may go to an infinite loop if you supply impossible combinations of row and column totals. With `quasiswap` you must also be very careful with data types, because it uses C code.

Here an overview of making your own function to generate random binary matrix with given marginal totals. At first, you can extract the function we use:
```R
(foo <- make.commsim("quasiswap")$fun)
function (x, n, nr, nc, rs, cs, rf, cf, s, fill, thin) 
{
    out <- array(unlist(r2dtable(n, rs, cs)), c(nr, nc, n))
    storage.mode(out) <- "integer"
    for (k in seq_len(n)) out[, , k] <- .C("quasiswap", m = out[, 
        , k], nr, nc, PACKAGE = "vegan")$m
    out
}
```
All `commsim` null models have identical call interface that is desribed in `?commsim`. In this case, you seem to need only `n` (number of simulated matrices), `nr`, `nc` (row and column dimensions), and `rs`, `cs` (row and column sums). The dimensions `nr` and `nc` are used in the C code, and you must take care that they really are of mode integer.  If your row and column totals (frequencies) are `delta` and `d`, you can generate one binary 20 x 20 matrix using:
```R
drop(foo(n=1, nr=20L, nc=20L, rs=delta, cs=d))
```
Please note `20L` which takes care that the values really are integers, and not only numeric. Beware of infinite loops! The current C code does not cope with them, neither do we check the result. Perhaps @psolymos and I should consider this.

**Comment by fmassol** [comment]
Wow, this is impressive. Thanks a lot for the code.
As far the problem of infinite loops is concerned, apparently Miklos & Podani were very sure that it would not appear, as they prove it in the Appendix B of their paper:
http://www.esapubs.org/archive/ecol/E085/001/appendix-B.htm
Thank you very very much for the help.

François

**Comment by jarioksa** [comment]
Their proof concerns transforming an existing matrix with certain marginal totals to another matrix with the same marginal totals. That is, you find the marginal totals from an existing matrix. However, it is possible to design marginal totals that cannot be derived from any matrix of zeros and ones: binary matrix with those marginal totals does not exist. In that case the Quasi-swap method can never reduce all numbers of zeros and ones, but it tries infinitely. We do not detect this case, and are not prepared of meeting one.

**Comment by fmassol** [comment]
In the most general case, apparently there is a simple set of conditions to verify on the sequences for them to be actual degree sequences of a bipartite graph (Gale-Ryser theorem). I just got hold of a copy of Brualdi & Ryser's (1991) book, and their theorem 6.2.4 gives this set of condition in a very general fashion (i.e. not restricted to square bipartite graph). As these tests do not look awfully complicated, I'll try and code them myself.

**Comment by jarioksa** [comment]
Sounds great. `r2dbinary` would be welcome in **vegan** -- or anywhere else. That could be built upon `quasiswap`, but as a user-level function really needs checking input.
