### ISSUE TITLE
Jaccard index (vegdist vs nestedbetajac)

### ISSUE THREAD

**Issue by murilomiranda** [vegandevs/vegan#183]
On average Jaccard index from vegdist-function with binary = TRUE is different from nestedbetajac, does someone know why?

**Comment by jarioksa** [comment]
Multiple-site dissimilarities (as Baselga defined them) are not equal to the mean of pairwise dissimilarities. See A. Baselga (2012), Global Ecology and Biogeography, 21, 1223–1232:

> Another enlightening conclusion that can be extracted from this example is the basic incorrectness of using the mean pairwise measures for computing multiple-site dissimilarities. ... I stress again the need to use multiple-site dissimilarity measures when the attribute of interest involves more than two sites, as the use of averaged pairwise measures can yield misleading results. (_pages_ 1230-1231).

**Comment by jarioksa** [comment]
There are two issues:

1. Multiple-site dissimilarities are **not** equal to average of pairwise dissimilarities. They are defined to be different (but I don't know why).
2. There was a buglet in the original code of `nestedbetajac` and `nestedbetasor` which made them give wrong results with quantitative data (binary data were OK). This was fixed in cb58f43f
