### ISSUE TITLE
Flaky Travis

### ISSUE THREAD

**Issue by jarioksa** [vegandevs/vegan#281]
It seems that Travis builds regularly fail for reasons unrelated to **vegan**. Either the reason is in Travis configuration files and changes in the items required, or then Travis is just flaky.

Personally I find little use of Travis checks because I run my own checks and just ignore Travis check results. However, it would be nice to have working Travis, and if impossible, then I suggest to remove Travis tests. False reports on failed tests are annoying.

The latest failed check is in https://travis-ci.org/vegandevs/vegan/jobs/379599252
This times it seems to be a problem in installing `libmagick++-dev` which is (was?) an object-oriented C++ interface to ImageMagick graphics manipulation software.

**Comment by jarioksa** [comment]
This seems to be a specific and known issue this time:

https://stat.ethz.ch/pipermail/r-sig-debian/2018-May/002856.html

However, Travis has been broken for long  period previously.

**Comment by gavinsimpson** [comment]
I don't recall very long outages before and the links with Travis and Appveyor are quite important to alert us to potential issues with R/R-devel.

I rarely get false reports and I don't see many (as I get the emails when you push changes and a build fails) as it is. The benefits outweigh the inconvenience of the odd false positive (you can always trigger the build again from the web interface of Travis, linked from the failure message).

I will double check our config to make sure we have the up-to-date structure etc and that we have the checks for the various R releases Travis supports (current and devel are important but previous release could also be useful give our discussions in other threads?)

**Comment by gavinsimpson** [comment]
Following a slightly rocky start (apologies for the failing *oldrel* builds) we are now checking

* current R release
* Rdevel snapshot (as determined by Travis)
* previous R release

I have cleaned up the config file to remove the codecov stuff that @jarioksa didn't like and was timing out a while back.

I will need to look at adding *ghostscript* to the list of `apt` packages that need installing as `R CMD check` is complaining that it can't check the sizes of some files.

**Comment by gavinsimpson** [comment]
There were a few issue with package dependencies of dependencies for those packages we reference in our Rd files. This is an issue with *nloptr* (needed by *lme4*) that I fixed by installing a system library via `apt` and *smacof*, which requires *wordcloud* which isn't available for `oldrel` so I have dropped *smacof* from the list of packages we install during the Travis build.

This all looks to be working properly now; just pushed these to the *master* branch and will follow up with the *cran-2.5* branch once the former passes OK.

**Comment by gavinsimpson** [comment]
I think the red crosses were issues with the r-devel build only (which was something related to Rcpp) (Travis declares the whole build failed if at least one of the R versions we build against fails). There was no problem with the R release build.

I don't know what the solution is to this? This isn't Travis' fault - there was a genuine issue somewhere in the set of packages we might reasonably need to check *vegan* (admittedly this could have been due to *knitr* or due to dependencies or dependencies etc. of packages we refer to in Rd files &mdash; I haven't looked too deeply at that.)

If we just want to build the package and check it with a minimal R package install, I can cut down to some extent the packages I force to be installed but we'll see a NOTE for crossref checks not able to be satisfied. That seems like a reasonable compromise, except one of us would have to make sure that we check this manually before submitting anything to CRAN as they'll reject a submission if the crossrefs are out of date.

**Comment by gavinsimpson** [comment]
It looks like all is well with the *master* branch so I'll make the same changes on the *cran-2.5* branch and see how we go for a while.

**Comment by gavinsimpson** [comment]
Both *master* and *cran-2.5* branches are now building OK on Travis for

1. `oldrel`
2. `release`, and
3. `devel`

I'll keep an eye on this and we can reduce packages to be installed if needed.
