### ISSUE TITLE
Delta variance and skewness in mrpp

### ISSUE THREAD

**Issue by ninadesianti** [vegandevs/vegan#301]
Why delta variance and skewness are not calculated in MRPP analysis using mrpp function in vegan? Is there any reason for not providing those values in the results?

**Comment by jarioksa** [comment]
One reason is that nobody has written code to calculate those. Why would those be needed and what is their meaning?

**Comment by ninadesianti** [comment]
They were provided in the result of MRPP using mrpp function in the Blossom package. I think they are used to calculate the T statistics.

**Comment by jarioksa** [comment]
The *t*-statistic (which is a parametric test statistic) can be found with `summary(permustats(<mrpp_result>))` in **vegan**. However, in **vegan** `mrpp` is one of non-parametric tests based on permutations. Main reason for this is  that`mrpp` deals with dissimilarities instead of observations, and for *n* observations you have _n_(_n_-1)/2 dissimilarities which means that parametric tests are biased when they take each dissimilarity element as an observation. Skewness is not involved in *t*-statistic. Please note that base **R** does not have a function for skewness, but all functions are in contributed packages. There is a reason **R** has no skewness function: it is not very useful, but you should have other means of inspecting data. In **vegan**, function `permustats` can be used to extract permutation statistics and it has several graphical tools plus numerical `summary`:
```r
> methods(class="permustats")
[1] boxplot     c           density     densityplot print       qqmath     
[7] qqnorm      summary   
```
All these can be used with `mrpp`.

**Comment by ninadesianti** [comment]
Thank you for the explanation, Jari!
My bad. I meant only the delta variance is used in T-stat.
