### ISSUE TITLE
results of marginal effects tests depends on syntax?

### ISSUE THREAD

**Issue by chrisblackwood1** [vegandevs/vegan#311]
Hi,
It looks to me like the p-values of marginal effects tests for RDA are providing different results depending on syntax used.  I thought that these methods should provide the same results, but maybe I am misunderstanding something.  Below are two examples; datasets are attached.  Thanks!

1. First is an example where the P-value for the marginal effect of the variable "Ecosystem" (after correcting for "Habitat") varies dramatically (from ~0.1 to <0.01).

1.1. Using formula interface and ANOVA with by="margin"
```javascript
> rda.inv.rare.hel.add=rda(inv.rare.hel[,11:204] ~ inv.rare.hel$Ecosystem + inv.rare.hel$Habitat)
> anova(rda.inv.rare.hel.add,by="margin")

Permutation test for rda under reduced model
Marginal effects of terms
Permutation: free
Number of permutations: 999

Model: rda(formula = inv.rare.hel[, 11:204] ~ inv.rare.hel$Ecosystem + inv.rare.hel$Habitat)
                       Df Variance       F Pr(>F)    
inv.rare.hel$Ecosystem  2 0.008882  1.9401  0.097 .  
inv.rare.hel$Habitat    1 0.047391 20.7043  0.001 ***
Residual               14 0.032045                   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

1.2. Using formula interface + Condition() followed by ANOVA
```javascript
> rda.inv.rare.hel.eco=rda(inv.rare.hel[,11:204] ~ inv.rare.hel$Ecosystem + Condition(inv.rare.hel$Habitat))
> anova(rda.inv.rare.hel.eco)

Permutation test for rda under reduced model
Permutation: free
Number of permutations: 999

Model: rda(formula = inv.rare.hel[, 11:204] ~ inv.rare.hel$Ecosystem + Condition(inv.rare.hel$Habitat))
         Df Variance      F Pr(>F)   
Model     2 0.008882 1.9401  0.005 **
Residual 14 0.032045                 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

1.3. Using X,Y,Z format followed by ANOVA (with numerically coded factors)
```javascript
> rda.inv.rare.hel.eco=rda(inv.rare.hel[,11:204], inv.rare.hel[,6:7], inv.rare.hel[,8])
> anova(rda.inv.rare.hel.eco)

Permutation test for rda under reduced model
Permutation: free
Number of permutations: 999

Model: rda(X = inv.rare.hel[, 11:204], Y = inv.rare.hel[, 6:7], Z = inv.rare.hel[, 8])
         Df Variance      F Pr(>F)   
Model     2 0.008882 1.9401  0.009 **
Residual 14 0.032045                 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

2. Second example is much more subtle, but running repeated tests reveals a consistently higher P-value when using the by="margin" syntax.  Below I run analyses similar to above to test the marginal effect of lake Area on fish composition.  This is repeated 50 times to get an average P-value for each method.

```javascript
> test=matrix(nrow=50,ncol=3)
> for(i in 1:50){
+ fish.hel.rda.all=rda(fish.hel[,12:29]~fish.hel$Ca + fish.hel$Secchi + fish.hel$Cobble + fish.hel$Area + fish.hel$MaxDepth)
+ test[i,1]=anova(fish.hel.rda.all,by="margin")$P[4]
+ fish.hel.rda.area=rda(fish.hel[,12:29], fish.hel[,9], fish.hel[,c(6:8,10)])
+ test[i,2]=anova(fish.hel.rda.area)$P[1]
+ fish.hel.rda.cob=rda(fish.hel[,12:29]~fish.hel$Area + Condition(fish.hel$Ca+fish.hel$Secchi+fish.hel$Cobble+fish.hel$MaxDepth))
+ test[i,3]=anova(fish.hel.rda.cob)$P[1]
+ }
> apply(test,2,mean)
[1] 0.11228 0.09704 0.09758
```
ANOVA with by="margin":     ave P=0.112288
ANOVA using X,Y,Z format:    ave P=0.09704
ANOVA with Condition() format:  ave P=0.09758

[marginal_effects_datasets.zip](https://github.com/vegandevs/vegan/files/3101400/marginal_effects_datasets.zip)

**Comment by jarioksa** [comment]
I cannot reproduce your example with the data supplied, and indeed, I cannot even run the last case, but I get an error of non-numerical data. The other two cases worked, but the numerical results were different. It seems that you have omitted several steps between your data and first line of code in your message. Can you please produce a complete running example.

However, I can explain the difference between first two cases. Firstly, you should use the same random number sequences in all cases. Either set the random number seed to the same value (`set.seed()`), or generate the permutation matrix to be used in all cases. I suggest the latter alternative because it makes easier to recycle same permutations between all cases.

Then about your two first cases: they indeed imply different permutation models (and this is documented in `?anova.cca`). The default permutation model in `anova.cca` is `model = "reduced"` which performs residuals **after** conditions in partial models. That means that the partial terms are **unpermuted** and model terms are permuted. In marginal test, all model terms are permuted similarly. To achieve comparable models for both, you must set `model = "direct"` in `anova.cca`. With the same random number seed (*i.e.*, the same permutations) and with direct permutation model, the results are numerically identical. In my test with your data the maximum difference between two permutations was of magnitude 10<sup>-13</sup> which is as close to zero as numerically possible in digital computers.

I cannot run the last case because your example is not reproducible, but if you fix the problems, I can have a look at it later.

**Comment by chrisblackwood1** [comment]
Thanks for the quick response.  Some follow-up thoughts on this issue are below.  But first, sorry about the confusion, when I wrote the dataset file out from R, an extra first column was added by write.csv.  So the column references in my code were all off by one.  The code below reproduces the output from my first message, with set.seeds added.

```javascript
library(vegan)    ## using vegan 2.5-4
inv.rare.hel=read.csv(...\\reduced_invert_dataset.csv)

rda.inv.rare.hel.add=rda(inv.rare.hel[,12:205]~inv.rare.hel$Ecosystem+inv.rare.hel$Habitat)
set.seed(10)
	anova(rda.inv.rare.hel.add,by="margin")

rda.inv.rare.hel.eco=rda(inv.rare.hel[,12:205] ~ inv.rare.hel$Ecosystem + Condition(inv.rare.hel$Habitat))
set.seed(10)
	anova(rda.inv.rare.hel.eco)

rda.inv.rare.hel.eco=rda(inv.rare.hel[,12:205],inv.rare.hel[,7:8],inv.rare.hel[,9])
set.seed(10)
	anova(rda.inv.rare.hel.eco)
```

Thanks for the clarification about the permutation models.  Now I understand the difference in output, and I see how to replicate both results using the same syntax as below.  
```javascript
rda.inv.rare.hel.eco=rda(inv.rare.hel[,12:205] ~ inv.rare.hel$Ecosystem + Condition(inv.rare.hel$Habitat))
	set.seed(10)
	anova(rda.inv.rare.hel.eco,model="direct")
	set.seed(10)
	anova(rda.inv.rare.hel.eco,model="reduced")
```
This also works for the X,Y,Z syntax, but I see their is no real "reduced" model implemented for the by="margin" syntax.

Which leads me to the following thoughts...The test for marginal effects is essentially a partial test, because it is a test with all other factors included in the model.  In fact, the results are identical if the permutation method is set the same (as above).

The by="margin" syntax is _very_ tempting, since all factors can be tested using one line of code instead of many.  But the permutation method implemented (method="direct") seems to be acknowledged in the literature as less powerful (going back to Legendre and Anderson 1999, also Legendre, Oksanen, and ter Braak 2010 for canonical axes).  
And very much less powerful for some particular datasets like mine!

So, it does not make sense to me to use this by="margin" syntax ever, as currently implemented.  It would seem to be rare for anyone to want to implement the less powerful test...particularly since the more powerful reduced model method is implemented for other (more cumbersome) syntax.

**Comment by jarioksa** [comment]
It is not only about being "powerful", it also about being correct and sensible: we do not want to get low _p_-values but correct _p_-values. An important point in permutation tests is that permutation is made by rows instead of permuting each variable independently. The variables are correlated, and we maintain these correlations when we permute rows. In reduced model, we assume that partialling variables (conditions) are correlated among themselves, and the constraining variables are correlated among themselves, but these two sets of data are uncorrelated. In direct model we also maintain the correlations between conditions and constraints. If you do "marginal" tests *via* a set of partial models, then you assume that all other variables (your current set of conditions) are correlated, but the tested variable is independent of all others when and only when evaluating its significance. This does not make sense to me and therefore we do not do so.

If you really think that _p_=0.112 is much worse than _p_=0.097, you should stop for a while and reconsider.

**Comment by chrisblackwood1** [comment]
Hi, I guess I should have started this thread by stating that I love the vegan package, use it all the time, and teach many grad students how to use it.  So, this is not hostility, just trying to get clarity on some features that are new to me, and potentially provide feedback in the forum that I thought feedback had been directed to.

For my invert dataset, the different approaches resulted in p-values of **0.1** and **0.005**.  Yes, I think this indicates that one approach is much worse in terms of power, _if_ they are equally correct and sensible.  And if they are, then it makes little sense to me to use the approach with consistently worse power, which is in line with every paper on evaluation of statistical approaches I have ever seen.

So, are they equally correct?  Starting with my particular dataset, my two explanatory variables (Ecosystem and Habitat) are uncorrelated factors.  So by="margin" would provide a test that is less powerful and, from your previous response about assumptions, this would be based on an unnecessary assumption that they might be correlated even I know they are not.  It seems that, with explicitly orthogonal explanatory variables, there is no reason to use the direct model, so one should not use by="margin" in that case.

But also, in the case of correlated constraints (Y) and partialled out conditions (Z), I don't yet see the case in the literature for using the direct model (or by="margin").  _Maybe I have stumbled into another difference in philosophy among the groups doing this work?_  The reduced model seems to be accepted and advocated for partial RDA due to better power and flexibility (e.g. Legendre and Anderson 1999 and Legendre and Legendre 2012).  And the assumption that Y and Z are uncorrelated is inconsistent with extensive literature from Legendre's group on testing variance components by partialling out variables.  Going forward from Borcard et al. 1992 and even CANOCO, it is assumed that conditions and constraints in partial RDA _are_ correlated, and that this is also captured in the species data (X).  The correlated part is explicitly indicated by "overlap" variance.  After the correlated part present in X is removed, the test proceeds on only that part of the variation in X that can be related to the uncorrelated part of Y.  If this interpretation and procedure for partial/marginal tests is adopted, which embraces correlations between Y and Z, then again I would like to use the more powerful, and historically usually implemented, reduced model test.  

Thanks for the help,
Chris
