### ISSUE TITLE
anova.cca not testing marginal effects for main terms when model contains interaction

### ISSUE THREAD

**Issue by marchtaylor** [vegandevs/vegan#318]
I think I may have come across a bug - when a cca model formula contains interaction terms, the main effects are not tested when `by = "margin"`. When  `by = "term"`, the main effects are correctly tested, e.g.:

```
data(varespec, varechem)
mod <- cca(varespec ~ (Al + P + K)^3, varechem)
# mod <- cca(varespec ~ Al + P + K + Al:K, varechem)

## overall test
anova(mod)
## tests for individual terms
anova(mod, by="term")
anova(mod, by="margin")
```

**Comment by jarioksa** [comment]
When you have interaction terms, the involved main effects are not marginal, and therefore they are not tested when you request tests of marginal effects. If you have terms `Al`, `K`, `Al:K`, the only marginal term is `Al:K`: it is a term that can be removed. Terms `Al` and `K` are not marginal because they are included in `Al:K`, and these terms cannot be removed.

The interpretation is the same as in standard `lm` and `glm` models and is based on the same basie **R** code.

**Comment by marchtaylor** [comment]
Thanks for the quick clarification
