### ISSUE TITLE
Error: protect(): protection stack overflow

### ISSUE THREAD

**Issue by katiemcconn** [vegandevs/vegan#323]
Hi there,

I am trying to run what is seemingly turning out to be a very large PERMANOVA by calling adonis in vegan in R 3.5.1.  In the script, which I am running off of our institution's large server, I first include a reduced version of the adonis, using the same data. Next, I include the adonis which includes all variables that I am testing, each of which has been meticulously scanned for missing data to remove.

When I read the output file, the first small adonis works great, but the full adonis terminates with the note: 

`Error: protect(): protection stack overflow`

I have tried using both  `--max-ppsize=500000` at startup of R and `options(expressions = 5e5)` from within R before the analysis, to no avail. Always the same error. Has anyone experienced this before? How did you get around it? Unfortunately our research group has decided that it is not statistically sound to analyze the variables in chunks, although that works in the adonis. 

Also, is there a difference between adonis and adonis2 that could be useful?

Thank you so much, I very much appreciate it! I can send you my script and files if requested. 

Cheers,
Katie

**Comment by jarioksa** [comment]
Protection stack overflows come Fromond compiled code which is outside Vegan (adonis has no compiled code on vegan). This is probably beyond out control. it mary help if we know the command that triggers this error. If YouTube step through with debugonce(adonis), you can find the offending line.

I’m on train travelling north (now at 67 deg N), and I may not respond immediately.

**Comment by katiemcconn** [comment]
Thanks for the swift reply. Below is 1) making the dist matrix 2) the small adonis call (working fine) and 2) the full function call (stack overflow error):

1. `vegcoralst <- vegdist(Coralfamilytemp_totu, method = "bray", na.rm = TRUE)`

2. `adonis(vegcoralst ~ TIMEPOINT*ENRICHED*SITE*GENUS*X15maxtemp*yearmaxtemp*INDIVIDUAL, data = Coralfamilytemp_metadta, permutations=999, method="bray")`

3. `adonis(vegcoralst ~ TIMEPOINT*ENRICHED*SITE*DEPTH*HABITAT*ISLAND_SIDE*GENUS*X15mintemp*X15maxtemp*X15meantemp*X15rangetemp*X15sdtemp*yearmintemp*yearmaxtemp*yearmeantemp*yearrangetemp*yearsdtemp, data = Coralfamilytemp_metadta, permutations=999, method="bray", parallel = getOption("mc.cores"))`

Also, I have tried 3. with and without `parallel`

Sincere thanks, and enjoy the Arctic

**Comment by jarioksa** [comment]
The first forensic analysis is to run `traceback()`. That will give you the call sequence that leads to the error. This is often sufficient to pinpoint the source of error.

Sometimes it is necessary to step through the function to find the source of error. You can start stepping giving first command `debugonce(adonis)` and then running your `adonis` command. This will probably lead you to some other function where the error happens. So issue `debugonce(errorgivingfunction)` and run `adonis` again.

I do believe that the ultimate error does not come from a **vegan** function, because you can only have protection stack errors from compiled code, and `adonis` does not use any compiled code of **vegan**.  However, we may be able to see what **vegan** submits to that external compiled code. 

Your formula defines a 16th degree interaction term and this may be too much to munch. Even if all your factors have only two levels, your model matrix would have 131,072 columns, and each extra level of a factor will double that number. So a protection stack of 500,000 may just not be enough.  This means that you try explain your dependent data with 131,072 predictor variables (and double that for each level of factor beyond 2) – and for a meaningful analysis, you need many more observations than predictors. Do you have such a large data set, or should you reduce the highest degree of interactions?

**Comment by jarioksa** [comment]
This seems to be a stale issue: no response to queries.
