### ISSUE TITLE
Why does protest() find a high correlation between seemingly significantly different data sets?

### ISSUE THREAD

**Issue by Antsushi** [vegandevs/vegan#335]
Assume that we have the following data

```
set.seed(123) 
Xmat <- matrix(rnorm(2000), ncol = 200, nrow = 10) 
Ymat <- Xmat[,1:6]
```
Where Ymat is subsampled from Xmat.

Running `protest() ` we get a high correlation between the two matrices

```
library(vegan)
pss <- protest(Xmat, Ymat, permutations=0)
pss


Procrustes Sum of Squares (m12 squared):        0.4318 
Correlation in a symmetric Procrustes rotation: 0.7538 
Significance:  1 

Permutation: free
Number of permutations: 0
```
How come, considering the large difference in the number of variables, the correlation is so high? Is the fact that Ymat is subsampled from Xmat has such a strong influence on the significance of the correlation?

This is something I found with my own data using` LaSEC()` from the package ` lambda`. The aim of the function is to assess "how many landmarks are enough to characterize shape and size variation", as per the author's paper.

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0198341

I found that with my own 2D landmark data, centroid size correlation can be as high as 98% when the centroid size of the subsampled data set has been derived from only 3 landmarks, compared to the 100 landmarks of the parent data set. I was also surprised to see that 20 landmarks out of 100 had a correlation of 90% with the original 100 landmarks!

**Comment by fabiomarroni** [comment]
I also noticed strange behavior in the computation of the pvalue. 
I link at my post on [biostars](https://www.biostars.org/p/412174/)

I tired to understand better: by looking at the code of protest it looks that what is being counted is how many times the value computed in the permutations (I couldn't understand what value is being computed there) is greater than `sol$t0` which is indeed the correlation, and not the sum of squares. Maybe this (or somewhere near) is the problem?

**Comment by gavinsimpson** [comment]
@Antsushi In short, yes. The procrustes rotation step involves a SVD of the matrix cross product. With the data as you defined, the resulting cross product matrix contains many similar elements. If we have

    XY <-  crossprod(Xmat, Ymat)

then the sub matrix `XY[1:6, 1:6]` is exactly the same as `crossprod(Xmat, Xmat)[1:6, 1:6]`:

```r
> head(crossprod(Xmat[,1:6], Ymat), 10)
           [,1]      [,2]       [,3]       [,4]       [,5]       [,6]
[1,]  8.2430260  5.302745 -3.5604929  3.2866793 -3.2461749  0.8311995
[2,]  5.3027448 10.133599 -5.8195203  2.0084826 -2.5669856  1.3334163
[3,] -3.5604929 -5.819520  9.6001545 -3.2988258  0.2424901 -4.7126324
[4,]  3.2866793  2.008483 -3.2988258  3.5395573  0.3548536  1.1245790
[5,] -3.2461749 -2.566986  0.2424901  0.3548536 10.5473698  1.3065105
[6,]  0.8311995  1.333416 -4.7126324  1.1245790  1.3065105  7.0929300
> head(crossprod(Xmat, Xmat)[1:6, 1:6], 10)
           [,1]      [,2]       [,3]       [,4]       [,5]       [,6]
[1,]  8.2430260  5.302745 -3.5604929  3.2866793 -3.2461749  0.8311995
[2,]  5.3027448 10.133599 -5.8195203  2.0084826 -2.5669856  1.3334163
[3,] -3.5604929 -5.819520  9.6001545 -3.2988258  0.2424901 -4.7126324
[4,]  3.2866793  2.008483 -3.2988258  3.5395573  0.3548536  1.1245790
[5,] -3.2461749 -2.566986  0.2424901  0.3548536 10.5473698  1.3065105
[6,]  0.8311995  1.333416 -4.7126324  1.1245790  1.3065105  7.0929300
```

Note that you don't have any significance here; you didn't do any permutations so no permuted values equal to or greater than the test statistic and hence your p-value is 1. We should probably change "significance" in the printed output as that is a frowned-upon term in statistics these days.

**Comment by gavinsimpson** [comment]
@fabiomarroni 

I'm not sure what your concern is? You say (in the Biostars post)

> By reading the pdf tutorial I understand that the greater the correlation (and the smaller the sum of squares), the lower the pvalue, which makes perfectly sense. However, this is the opposite of what I observed with my data.

but that's not what your example shows: (with `set.seed(1)`)

```r
> self

Call:
protest(X = mymat1, Y = mymat1) 

Procrustes Sum of Squares (m12 squared):            0 
Correlation in a symmetric Procrustes rotation:     1 
Significance:  0.001 

Permutation: free
Number of permutations: 999

> other

Call:
protest(X = mymat1, Y = mymat2) 

Procrustes Sum of Squares (m12 squared):        0.624 
Correlation in a symmetric Procrustes rotation: 0.6132 
Significance:  0.084 

Permutation: free
Number of permutations: 999
```

So we find perfect correlation and *zero* sums of squares difference in `self`, and the p-value is as small as it can be with 999 permutations (0.001; only 1 (the observed statistic) of the 1000 test statistics from null distribution (999 randomised versions plus 1 for the observed) is as large or larger than the observed value).

In `other` we find that with two different matrices there is *lower* correlation and **higher** sums of squares; i.e. these two matrices are not identical under location, scale, and rotation transformations. The p-value suggests that about 8 times in 100 you'd get the same test statistic (similar correlation) if you randomised one of the matrices.

The number of permutations here is a little large to do all possible permutations of the data but it can be done in a couple of mins (basically the time it took me to write the last paragraph):

```
> perms <- how(complete = TRUE, maxperm = factorial(9) + 10)
> other

Call:
protest(X = mymat1, Y = mymat2, permutations = perms) 

Procrustes Sum of Squares (m12 squared):        0.624 
Correlation in a symmetric Procrustes rotation: 0.6132 
Significance:  0.072768 

Permutation: free
Number of permutations: 362879
```

which doesn't meet the arbitrary threshold for "statistical significance".

All this test can show is whether the Procrustes statistic (the correlation) is large relative to a set of values for the test statistic drawn from the null distribution of the test statistic &mdash; where we are shuffling the rows of `X` and comparing them with `Y`.

**Comment by jarioksa** [comment]
I haven't looked at this earlier, but I really cannot find anything wrong with the `protest()` function. It is possible to find a rotation and scaling of `Ymat` that gives that high correlation. What happens within `protests` is that we scale both matrices to zero sum and unit norm (sum of all elements is zero and sum of squared elements is 1). Then we rotate and scale `Ymat` so that it comes elementwise as close to `Xmat` as possible. Please note that we do not have anything like *adjusted* _R_<sup>2</sup>, but it is just an ordinary _R_<sup>2</sup> and for small data sets (10 rows) and high number of dimensions we expect do *much* better than _R_<sup>2</sup>=0.

The pre-standardizations we do in `protest` are (using `Xmat` and `Ymat` of your original posting):
```r
X <- scale(Xmat, scale = FALSE) # center to zero sum
Y <- scale(Ymat, scale = FALSE)
X <- X/sqrt(sum(X^2)) # scale to unit sum of squares
Y <- Y/sqrt(sum(Y^2))
```
Then we submit these two `procrustes()` analysis. Let us not look at its result directly, but just see how well it could scale and rotate `Y` to fit `X`:
```r
m <- procrustes(X, Y)
ss <- sum((X - m$scale * Y %*% m$rotation)^2) # residual SS
sqrt(1-ss) # R-squared
# [1] 0.7537787
```
Above we applied the `scale` scalar and `rotation` matrix of the Procrustes analysis directly on the input matrices `X` and `Y` (even ignoring centring) and we got the same _R_<sup>2</sup> as in your example (but with more decimals). 

As to permutation test: there was no problem there either: the `t0` that we used is rank-order identical to _R_<sup>2</sup>, but we can have slightly faster permutation tests after this transformation (and actually, we could have even faster permutation tests). 

Your expectation of _R_<sup>2</sup> = 0 was wrong. It is just the same issue that same issue that some people try to handle with adjusted _R_<sup>2</sup> in linear models with small data sets and high dimensionality. In particular with small data sets you must expect _R_<sup>2</sup> >> 0.

**Comment by fabiomarroni** [comment]
Now I understand. My problem was really basic (i.e. stupid), because in spite of reading it in the tutorial, in the manual and in the papers that you reference (even in the title of Peres-Neto!), I insisted expecting that protest was testing _difference_ while it is instead testing _similarity_. I am really sorry about my misunderstanding.

**Comment by gavinsimpson** [comment]
@fabiomarroni No problem. Glad this helped clarify what was going on.
