### ISSUE TITLE
ANOSIM error in vegan

### ISSUE THREAD

**Issue by kuldeepmore10** [vegandevs/vegan#336]
I am running a code for NMDS. This code I have used many times before. All of a sudden today it gives the error
```r
 "Error in anosim(F.dist, Climate1) : 
  there should be replicates within groups"
```
 where Climate1 is my environmental variable. I tried the same for the old files for which it used to work. But its not working for those files either. 
I used following code. 

```
 >F.dist <- vegdist(Frel)
> F.ano <- anosim(F.dist, Climate1)
```
What is the problem you think? I can't figure it out.

**Comment by jarioksa** [comment]
This was indeed changed so in vegan 2.5-3 for the reasons given in [StackOverflow](https://stackoverflow.com/questions/52082743/). ANOSIM needs both between-class and within-class distances, but before 2.5-3 it worked silently when there were no within-class distances. This was a user error, but it was not detected, and meaningless results could be reported. This error happens if the classification variable (your `Climate1`) has unique values for every observations so that you only have classes with one member each. If this is not the case with your variable, we need a reproducible example to find the reason for the problems.

NB., your question does not handle NMDS and you have not used any function for NMDS: I suggest you fix the header for your question.

**Comment by kuldeepmore10** [comment]
Dear Jari, 
Thank you very much. This is indeed helpful. I will change variable classification and will try out again! 
Also thank you for changing title from NMDS to ANOSIM.

**Comment by kuldeepmore10** [comment]
Dear Jari,

I have assigned my variables as following 

variable| Climate1 | Climate2
-- | -- | --
CIG3 | 1 | 11
CIG4 | 2 | 11
CMG3 | 3 | 12
CMG4 | 4 | 12
SEDIMENT3 | 5 | 13
SEDIMENT4 | 5 | 13
TIG3 | 6 | 14
TIG4 | 7 | 14
TMG3 | 8 | 15
TMG4 | 9 | 15
Water3 | 10 | 16
Water4 | 10 | 16

for both climates I got the message "Error in anosim(F.dist, env$Climate2) : 
  dissimilarities have 6 observations, but grouping has 12"
I dont know what to do now. Do I need to change my species table? If so how? I do have species with only one variable present in the table. Is that a problem?

**Comment by jarioksa** [comment]
I think the error message is clear: your dissimilarities are based on 6 observations, but your climate data has 12 observations. The data sets do not match. You should have the same observations in both cases: dissimilarities of 12 observations, or climate data f 6 observations.

**Comment by kuldeepmore10** [comment]
Thanks Jari. Solved the problem!
