### ISSUE TITLE
WA Scores in dbrda function?

### ISSUE THREAD

**Issue by jonpeake** [vegandevs/vegan#358]
I've been going down a bit of a rabbit hole with this one. Based on the internal code, the default site scores for dbrda (based on McArdle and Anderson 2001) are WA scores. These scores appear to be calculated using the same method for the capscale version of distance-based RDA (based on Legendre and Anderson 1998) of projection of Y on the eigenvectors u. However, in the dbrda version, Y is Gower's centered matrix and u are the eigenvectors of decomposed HGH, whereas in capscale Y is the original data and u are the eigenvectors from an RDA of PCO axes. WA scores in capscale therefore appear to make sense as true weighted averages of species scores by site, whereas the WA scores in dbrda don't appear to make statistical sense. Is this an artifact from previous versions of vegan, or if not, can you explain the process of multiplying G by the HGH eigenvectors?

Code referenced (Lines 227-234 of ordConstrained.R in source):
```
     ## wa scores
     if (DISTBASED) {
        wa <- Y %*% u[, posev, drop = FALSE] %*%
            diag(1/lambda[posev], sum(posev))
        v <- matrix(NA, 0, sum(posev))
    } else {
        wa <- Y %*% v %*% diag(1/sqrt(lambda), sum(posev))
    }

```

**Comment by jonpeake** [comment]
So it appears that using a metric distance calculation, WA scores for capscale are equal to the WA scores for dbrda, so I'm guessing the math checks out somewhere and WA scores are valid for dbrda. I think I have a gist of an idea why this works, but I would welcome a more mathematical/statistical explanation (and it could also be useful to include an explanation in the documentation so others don't go down the same rabbit-hole I did).

**Comment by jarioksa** [comment]
It is a long time since I implemented this, and I didn't find my notebook when thinking about this. However, the basic idea is that in unconstrained analysis (PCA), the final stable solution has dual relationship: (1) **v** = **Y<sup>T</sup>u Λ<sup>-1/2</sup>** and (2) **u** = **Yv Λ<sup>-1/2</sup>**. If we put **v** from (1) into (2), we get **u** = **YY<sup>T</sup>u Λ<sup>-1</sup>** (with **vegan** internal notation where **u** and **v** are orthonormal scores matrices for sites and species with eigenvectors as columns, **Y** is centred (and standardized) data matrix, and **Λ** is diagonal matrix of eigenvalues). For Euclidean distances, HGH of dbRDA is essentially just **YY<sup>T</sup>** (as long as you take care of correct scaling by *n*–1 in **vegan** result), and dbRDA treats all dissimilarities like they were Euclidean distances.  In constrained analysis (RDA) this stable dual relationship is broken, and we do not get **u** back from **v**, but **v** gives WA (or in this case, weighted sum) scores **wa**. However, thanks to this stable dual relations (**u** -> **v** -> **u**) we can analogously have **u** -> **v** -> **wa** even if we by-pass explicit use of **v**, and scale with  **Λ<sup>-1</sup>**. With Euclidean distances this gives the same results as RDA (even without species scores **v**), and dbRDA just treats any dissimilarities as they were Euclidean.

**Comment by jonpeake** [comment]
Very interesting, thank you for the thorough explanation! I saw there was talk a few years back about deprecating capscale in favor of dbrda, is that essentially because of this point that dbrda produces identical results to capscale when given Euclidean dissimilarities, but better results when given non-Euclidean dissimilarities? And if dissimilarities are not Euclidean but instead semi-metric (such as un-transformed Bray-Curtis), is the analogy still valid and thus wa scores are still viable, or is it suggested to use LC scores in that case (or, would it be more prudent to yield the dbrda method to the capscale method for plotting purposes)?
