### ISSUE TITLE
metaMDS hangs after I updated to 20.04????

### ISSUE THREAD

**Issue by sapuizait** [vegandevs/vegan#366]
Like the title says I ve been having problems running the metaMDS function of vegan since I updated to the latest ubuntu 20.04.
Yes I know it sounds weird but I swear I did not have any problems before (until last weekend I was running Ubuntu 18.04) and now I suddenly do!
Whenever I try to run 'metaMDS(Srare, distance="bray")' in Rstudio 1.3.959 using the vegan package 2.5-6 it hangs..... The fan of my laptop gets possessed and starts running amok and nothing happens! I cannot even quit Rstudio, i have to restart the computer!
I will be very happy to provide the input file "Srare" that I am using if you provide me an email address, do not want to post it publicly
Thanks for any help in advance
Cheerio
S

**Comment by gavinsimpson** [comment]
If you upgraded Ubuntu in place (rather than a fresh installation that nuked your home folder), did you reinstall all of your packages too? It's very easy to get into a mess when upgrading on Linux if you have compiled packages from source as moving from one version of a Linux distro to another often involves changes in the underlying compilers and system libraries which renders packages compiled against the old version broken.

**Comment by sapuizait** [comment]
damn, upgrade... Do you think if i purge all packages and reinstall it may fix it?

**Comment by jarioksa** [comment]
It may fix. In particular, if you had a major upgrade of **R**, all packages with compiled code may need to be re-installed to recompile the source so that they work with **R**. `metaMDS`  function in **vegan** is based on such compiled code which must be binary-compatible with your new Linux & **R**. Anyway, I do not believe that having your data would help us to solve the problem because our installations work OK, and this change probably is not data-dependent but **R** version-dependent.

**Comment by sapuizait** [comment]
OK thanks, will purge everything and reinstall R and packages from the beginning

**Comment by sapuizait** [comment]
just in case someone else encounters this, problem is solved. Removed all packages using .libPaths(), removed R using apt remove r-base and r-base-core and rstudio. Restart, reinstall and stuff are working again! pffff dodged a bullet there
