### ISSUE TITLE
ANOSIM error message

### ISSUE THREAD

**Issue by iroczgirl** [vegandevs/vegan#377]
Hello everyone,

When running the anosim function as laid out in the example:

```r
data(dune)
data(dune.env)
dune.dist <- vegdist(dune)
dune.ano <- with(dune.env, anosim(dune.dist, Management))
summary(dune.ano)
plot(dune.ano)
```
When executing line 4, I keep getting the following error:

```r
Error in tapply(x.rank, within, mean) : arguments must have same length
```
What could be the cause of this error, and is there a fix?

Thank you.

**Comment by jarioksa** [comment]
I don't get this error, but the commands runs smoothly.

I think it is best you check your data sets: you may have edited versions of `dune` or `dune.env` in your workspace.

**Comment by iroczgirl** [comment]
Thank you for the response!

The datasets are not edited.

However, I'm still running R version 3.6.2. Could that be the issue?

**Comment by jarioksa** [comment]
This is a standard **vegan** example, and it is run in regular CRAN check of **vegan**, and certainly would be flagged as an ERROR when it fails. I also ran it in my computer and had no problem. The error message is also clear: "arguments must have same length", and the only way they can have different lengths is that distance matrix and factor do not match. In clean environment you get the following:
```r
> attr(dune.dist, "Size")
[1] 20
> with(dune.env, length(Management))
[1] 20
```
That is, both are 20. If you get something else, then the problem is with your data.

**Comment by iroczgirl** [comment]
Thank you for your response.

That is exactly what I got in my environment.
However, I decided to upgrade R to the latest version, and wiped my environment clean.
After doing those tasks the commands functioned as intended.

Thank you!
