### ISSUE TITLE
Add vegandevs to r-universe.dev

### ISSUE THREAD

**Issue by psolymos** [vegandevs/vegan#392]
@jarioksa and @gavinsimpson : first of all, Happy New Year!

I just looked at [r-universe](https://r-universe.dev/help/). It is currently in testing phase and Jeroen Ooms will present it in a few days at the RStudio Global conference. It might be a CRAN-like option for folks to install development version of vegan (i.e. via specifying `repos` in `install.packages()` and not using the remotes package or maintain our own drat repository). Setup can be done by the vegandevs organization owner: https://github.com/apps/r-universe/installations/new

**Comment by jarioksa** [comment]
Sorry for my slow reaction. In the meantime I tried this with my private packages. However, I checked with my private non-CRAN packages, but they seem not be qualified to this universe and nothing happened. I have nothing against this, but can you explain what does this provide to already existing facilities? You can use `install_github` already now so what is the advantage of this? Most importantly, the main obstacle of using github version is that **vegan** contains C and Fortran code, and you need a compiler for these. R-universe only provides links to source code and gives no relief to this problem. Anybody who wishes to push **vegan** to the R-universe can do so, but I won't do this, because I do not understand the system.

**Comment by psolymos** [comment]
Hi @jarioksa thanks for checking. The r-universe is also a rather new initiative, so it is OK to put it off and see where things are going.

**Comment by jarioksa** [comment]
@psolymos fine!
