### ISSUE TITLE
Suggestion: adding the group argument to diversity()

### ISSUE THREAD

**Issue by oldi** [vegandevs/vegan#393]
The group argument in specnumber() is very useful but it is missing for the diversity function. Yet calculating an index per group is what is regularly done, and it could speed up many processes for calculating diversity data . Hence, I suggest adding the group argument to diversity().

**Comment by jarioksa** [comment]
This was also suggested in [StackOverflow](https://stackoverflow.com/questions/44376286/diversity-indices-by-treatment-groups-and-sites-in-r). Then I did not implement this since I think it could confuse users: they use the argument, and get a (correct) result that they did not want. However, I could add this, but what do you mean with diversity by `groups`: average diversity of sampling units in a group, or the diversity of average (or sum of) sampling units in a group? I would think about the latter, but I'm afraid that many users would think that they get the first if they use this argument.

**Comment by oldi** [comment]
You are right, I did not realize that the diversity value per group has to be something like the *average* Shannon value. I think this will really be confusing if it is not clear how the values are derived. Your suggestion of using the pooled diversity might then be even more confusing? Maybe it is better to leave it like it is and let the user work with the diversity output per sample.

**Comment by jarioksa** [comment]
Despite you giving up, I added that option to `diversity`. We have canned alternatives for partitioning diversity (`adipart`, `multipart`), and the `groups` argument is consistent with those (even with the "weighting" argument that I find strange). I also made those functions a bit easier to use.
