### ISSUE TITLE
Obtaining residuals from metaMDS

### ISSUE THREAD

**Issue by dianalg** [vegandevs/vegan#402]
Hello,

I am working on a NMDS plot of OTU data, and I have been having some trouble getting metaMDS to converge. I am curious if some small number of my samples might be driving this non-convergence, and possibly high stress values as well. To explore this question, it seemed reasonable to me to 1) identify which pairs of samples have relatively large differences between their dissimilarities and their distances in the final NMDS plot (i.e. large residuals), and 2) identify which samples have the largest residuals when metaMDS uses procrustes to compare the final two best solutions. I'm having a hard time figuring out how to do either of these things. My questions are: 1) Are the residuals from the final regression returned by metaMDS? I know I can basically visualize these using stressplot, but I can't seem to find the actual numbers. 2) Is there some way to match these residuals back to the samples that were being compared in the original distance matrix? 3) Is there some way to view the residuals from the final procrustes analysis (e.g. by returning an object of class procrustes or at least being able to label the points in the plots produced by the plot=TRUE option in metaMDS)? 

It's probably worth noting that I've already spent a significant amount of time playing with the options suggested in the metaMDS docs under Convergence Problems (e.g. previous.best, k, maxit, sratmax, noshare). 

I've included an example data set and code below, if it's at all useful. And thanks.

 **DATA**
[otu.txt](https://github.com/vegandevs/vegan/files/6152776/otu.txt)

**SAMPLE CODE**
```R
library(vegan)

otu <- read.table('otu.txt', sep=',', row.names=1)

set.seed(42)
otu.ord <- metaMDS(otu, distance='bray', k=2, trymax=50, autotransform=F, plot=T)
otu.ord$stress
```

**Comment by jarioksa** [comment]
Function `goodness` returns the contributions of points to the stress:
```r
goodness(otu.ord)
```
These contributions are defined so that sum of their squares is equal to squared stress.  Graphically you can inspects the rogue points with:
```r
plot(otu.ord, type="n")
## cex gives the size of points, and you have to multiply (50 here) to get visible points
points(otu.ord, cex=goodness(otu.ord)*50
```

Function `stressplot` returns the data set it uses:
```r
res <- stressplot(otu.ord)
```
Here item `res$x` are the input dissimilarities, `res$y` the matching distances in the ordination, `res$yf` are the fitted values shown as the step line in `spressplot`. So the raw residuals of points are `res$y - res$yf`, but `goodness` does some tricks on them to adjust them to match the stress.

However, rogue points may not have large contribution to the stress, because they are influential and change the configuration to suit them. You may use `metaMDS(..., plot=TRUE)` which will plot a Procrustes plot of every almost similar solution, and there you can see if there are just single points that move between solutions.
