### ISSUE TITLE
Grouping for categorical values in envfit 

### ISSUE THREAD

**Issue by sarahisherb** [vegandevs/vegan#403]
Hi, I am trying to create explanatory variable vectors using envfit, and I managed to do it for numerical data: 

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/81591832/112899148-bd079780-90af-11eb-9d3f-240f5335d7e7.png)

But for categorical data, I have this: 
![image](https://user-images.githubusercontent.com/81591832/112899200-d1e42b00-90af-11eb-99ff-2f64631e37a8.png)

I'm not sure what I can do to group by each variable, such that I get one arrow for each variable type? So one arrow for "Type", another arrow for "Class", "Area", etc. Is envfit able to get a mean for the MDS scores by variable type for example? 

Sorry if this is an easy question but I'm very new to R.

**Comment by jarioksa** [comment]
Arrows or "vectors" show the increase in the values of _continuous_ variables. You cannot have such an increase for class variables such as `Type`. What would an arrow mean for `Type`? What is the quantity that increases in `Type`? Therefore we do not calculate arrows for factors but we calculate the mean for the ordination scores for the _levels_ of a factor. The first pair of numbers in your table shows that average or centroid for `Type` level `EndophytesLeaves` and it would be in the centre of those points labelled as such in your graph. It would make no sense to have such a value for all `Type`, because `Type` will involve all your points, and their average scores (with no missing values) will be 0, 0 for any factor.

**Comment by sarahisherb** [comment]
Yeah, that makes sense. Thanks!
