### ISSUE TITLE
arrow = TRUE and length are not in the list of arguments of text.cca

### ISSUE THREAD

**Issue by jszhao** [vegandevs/vegan#420]
Hi there,

In the following example (it actually from `?plot.cca`).
```
     data(dune)
     pca <- rda(dune)
     pl <- plot(pca, type="n", scaling="sites", correlation=TRUE)
     text(pl, "sp", arrow=TRUE, length=0.05, col=4, cex=0.6, xpd=TRUE)
```

I think the plot is correct, however, I got the following warning message:
```
Warning message:
In text.default(sco, labels = rownames(sco), ...) :
  "length" is not a graphical parameter
```

I know the `length=0.05` is used to control the length of arrows. However, I don't find a argument of `length` in `text.cca` function:
```
     ## S3 method for class 'cca'
     text(x, display = "sites", labels, choices = c(1, 2),
          scaling = "species", arrow.mul, head.arrow = 0.05, select, const,
          axis.bp = FALSE, correlation = FALSE, hill = FALSE, ...)
```

In the help page, I think `head.arrow` is the argument that do the thing, however, when I replace `length` with `head.arrow`, I got more warnings:
```
Warning messages:
1: In arrows(0, 0, sco[, 1], sco[, 2], ...) :
  "head.arrow" is not a graphical parameter
2: In text.default(sco, labels = rownames(sco), ...) :
  "head.arrow" is not a graphical parameter
```
And the length of arrow is very long (0.25? the default length in `arrows` function).

The other question is I don't find the argument of `arrow = TRUE` in the argument list of `text.cca`, however
```
text(pl, "sp", arrow=TRUE, length=0.05, col=4, cex=0.6, xpd=TRUE)
```
have the argument of `arrow = TRUE`.

Any hints? Thanks!

Best wishes,
Jinsong

**Comment by jarioksa** [comment]
You do not use `vegan:::text.cca` in your example: the function would be used for your RDA result object `pca`, but you use `text(pl, ...)` where `pl` is an object of class `"ordiplot"` for which we use `vegan:::text.ordiplot` function. Currently `text.cca` refuses to use arrows for species or anything but biplot or regression scores arrows (but you didn't use that either). Function `text.ordiplot` will bow to your will and can use arrows for species, and these know argument `length` (`head.arrow` is only used in `text.cca`, but you do not use that function). There will be a warning because we pass extra parameters (such as `length`) to other functions via dots (`...`) and as there are several embedded functions, some of these will not know all these extra parameters. So they issue a warning which is harmless. This could be fixed, but I am not worried about those warnings – they are a design feature. I know that @gavinsimpson is worried about these warnings: perhaps he will have a look at the issue.

**Comment by gavinsimpson** [comment]
I can take a look at suppressing the warning message. As @jarioksa says, these are harmless and an annoyance of the way passing arguments via `...` works when you are passing them to multiple graphics functions. We already have functionality in {vegan} to handle this kind of thing, so I presume that either we missed converting `text.ordiplot` at the time or this was added after we did the initial conversion.

**Comment by gavinsimpson** [comment]
This is now "fixed" in the GH version. I won't port the changes to the 2.5 branch as these aren't critical problems and we should think about releasing 2.6 rather than spending time on more releases in the 2.5 branch (all else equal, and other than to fix important bugs that require a quick release).
