### ISSUE TITLE
Formula used in Diversity's Simpsons index calculation

### ISSUE THREAD

**Issue by ChristyPeterson** [vegandevs/vegan#512]
I have noticed that the simpson's index calculation in diversity is based on the formula of `D=1- sum(( n/N ))^2)` where n is the count of individuals for that species and N is the sum of individual for the population (sampling with replacement). However, there is another version where `D=1- sum ( n(n-1)/ N(N-1))` (sampling without replacement). Was the former formula chosen as it was computationally easier to calculate? 

I ask because the choice of sampling with or without replacement doesn't matter much at large numbers, but can matter significantly with smaller populations (as is sometimes the case in microbial typing, and in my case specifically). I'm also unsure if this was covered in the paper that the vegan diversity vignette points to ( Hill, 1973) but I'm unable to verify since its behind a pay wall.

**Comment by jarioksa** [comment]
The form was selected because it can be use any general non-negative data, and the form you suggested only applies to genuine counts of individuals (integer data). The form you suggested is available in function [`simpson.unb`](https://github.com/vegandevs/vegan/blob/master/R/simpson.unb.R)  which uses different mathematic formulation, and the numerical results may differ up to magnitude 10<sup>-12</sup> between formulae. This was released only recently, and you may need to upgrade **vegan** to access the function, or in the older **vegan** you can follow the Example for calculating unbiased Simpson (see change in commit e275ed6797330e50684a513b3d9a81e4eb6957d4).

**Comment by ChristyPeterson** [comment]
Thanks so much for the clarification! Makes sense that you would choose the version that allows for general data instead of genuine counts only. I'll look into the simpson.unb function. I'm pretty new to doing this type of analysis and frankly it took far to long to even figure out that there WERE two different ways of solving for Simpson's, so I really appreciate your pointing me in the right direction.
