### ISSUE TITLE
Adding Yue-Clayton index

### ISSUE THREAD

**Issue by antagomir** [vegandevs/vegan#525]
I suggest to add Yue-Clayton (dis)similarity index ([Yue & Clayton (2005)](https://doi.org/10.1080/STA-200066418)) as a new vegan::vegdist option. This is used in microbial ecology at least.

I already drafted the first version and did preliminary testing. This would complement the Aitchison and robust Aitchison distances that we contributed to _vegan_ earlier this year.

If Yue-Clayton contribution is welcome to the _vegan_ package, I could open a PR?

**Comment by jarioksa** [comment]
After quick reading, this "new" index seems to be identical to the "similarity ratio" of D. Wishart (1969) _Clustan 1A manual_ which was very popular in vegetation science in the 1980s. The divisor of Yue & Clayton eq. 2.1 is &Sigma;(_p_<sup>2</sup> – _q_<sup>2</sup>) + &Sigma;_pq_ which expands to &Sigma;_p_<sup>2</sup> + &Sigma;_q_<sup>2</sup> – 2&Sigma;_pq_ + &Sigma;_pq_ = &Sigma;_p_<sup>2</sup> + &Sigma;_q_<sup>2</sup> - &Sigma;_pq_. This can be found as `designdist("J/(A+B-J)", terms="quadratic")`.  This is a "quantitative Jaccard" with quadratic terms and advocated by Eddy van der Maarel (chief editor of _Vegetatio_ and then _Journal of Vegetation Science_) as "similarity ratio" from 1979 or something (I was in his Nordic course in Uppsala in 1979 and learnt the index there). **Vegan**  `vegdist` has now "quantitative Jaccard" with minimum terms, and although I knew this "new" index since 1980s I had decided not to implement it since it uses quadratic terms – which in general are suboptimal in community ecology because they emphasize single large differences. I have also been slow to implement in `vegdist` methods that can be easily calculated in `designdist`.  However, I'm open to different opinions. Next release version of **vegan** should be out soon (I have been busy with the **Hmsc** package – for which I'm paid for – and therefore **vegan** is delayed from its original plan of having the next release already some days ago).

It always nice to see that people find "new" indices that were published 53 years ago – and I think there may have been _prior art_ even before Wishart 1969.

**Comment by jarioksa** [comment]
The "new" Yue & Clanton index (their equation 2.1, first form) can be written in **vegan** as `designdist("J/(A+B-J)", terms="quadratic")`. This is a similarity index and it is identical to *a* similarity ratio in David Wishart's [CLUSTAN software ](https://www.st-andrews.ac.uk/itsnew/newsletter/1999/03/clustan.html) at least since Clustan 1A manual 1969. It was very popular in vegetation ecology in the 1980s, mainly because it was advocated by Eddy van der Maarel (chief editor of _Vegetatio_ and later of _Journal of Vegetation Science_) as *the* similarity ratio. It is a similarity index, but easily transformed to a dissimilarity as `designdist("(A+B-2*J)(A+B-J)", terms="quadratic")`. For binary data, it indeed reduces to Jaccard. **Vegan** has now a "quantitative Jaccard" in `vegdist` using *minimum* terms instead of quadratic, or `designdist((A+B-2*J)/(A+B-J)", terms = "minimum")`. I knew quite well van der Maarel's similarity ratio, but did not want to implement it because quadratic terms emphasize single large differences and are therefore suboptimal to most community data sets, and opted instead for the current quantitative `"jaccard"`. However, I had used it very often in 1980s, and learnt about it in a Nordic ecology course in Lund in 1979 (Eddy van der Maarel and ingenious Dick Clymo). It would be very easy to implement this method in `vegdist` but I do think this is worse than current `method = "jaccard"` (with minimum terms), and I'm also a bit reluctant to implement methods that can be easily expressed with `designdist`.

I find it elating that methods from 1969 (53 years ago) are suggested as new. Yue & Clayton paper is from 2005, so they were repeating Wishart only 36 years later. In general, I think that if you suggest a simple (dis)similarity index that uses terms &Sigma;_p_<sup>2</sup>, &Sigma;_q_<sup>2</sup> and &Sigma;_pq_, do not assume that it is something new that was never before invented. I think the reason Wishart called this **a** similarity ratio was that he thought that this was not novel in 1969 but invented many time before.

Not a very enthusiastic response, but I'm open to diverging opinions, and can change my mind. The next **vegan** release will be out "really soon now", so decisions must be reached out soon. **Vegan** would have been released already, but I have been busy with another package ([**Hmsc**](https://github.com/hmsc-r/HMSC)) where they pay for my work (unlike for **vegan**).

**Comment by antagomir** [comment]
I think this is interesting and nails it down well. I wonder if they had new interpretations in the 2005 paper, although it was pretty short anyway. 

Perhaps this issue can be closed until it can be argued that something else than `designdist` would be essential. Thanks!

**Comment by jarioksa** [comment]
The paper has a good and thorough discussion of statistical properties of the proposed index. I think this could be serve as a model of similar analysis of several other indices with quadratic terms.
