### ISSUE TITLE
Error in if (R2.adds[best] > R2.previous && (!R2scope || R2scope && R2.adds[best] <=  :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by eggxo** [vegandevs/vegan#610]
Dear jarioksa,
I meet an error: Error in if (R2.adds[best] > R2.previous && (!R2scope || R2scope && R2.adds[best] <=  :    missing value where TRUE/FALSE needed when I run ordiR2step. It seems the test reached the \<none\>, then the program Execution halted.
How could I solve this problem? Thanks alot! (below are  the log and my command)

command:
RDA0 <- rda(gen ~ 1,  Variables)
save(RDA0,file="RDA0.data")
RDAfull <- rda(gen ~ ., Variables)
save(RDAfull,file="RDAfull.data")
mod <- ordiR2step(RDA0, RDAfull, Pin = 1, R2permutations = 1000, R2scope = F)

log:
Step: R2.adj= 0.4143618 
Call: gen ~ UVB4 + sradthrid7_9 + sradfirst1_3 + UVB3 + sradsecond4_6 +      Organic + sradfour10_12 + vaprsecond4_6 + sradannual + CECSOL_M_mean +      PHIHOX_M_mean + K + UVB5 + windthrid7_9 + P + vaprfirst1_3 +      elev + windsecond4_6 + windfour10_12 + UVB2 + vaprfour10_12 +      vaprannual + OCDENS_M_mean 
 
R2.adjusted
\<none\>   0.4143618

Error in if (R2.adds[best] > R2.previous && (!R2scope || R2scope && R2.adds[best] <=  : 
  missing value where TRUE/FALSE needed
Calls: ordiR2step
Execution halted

**Comment by jarioksa** [comment]
There is no reproducible example, but I can reproduce this with overfitted models that have not residual variation (no residual unconstrained component). In those cases `RsquareAdj` will return `NA`. Is this the case with your full model (`RDAfull`)? Normally the function will stop earlier, but if you set `Pin=1` and `R2scope=FALSE` it will indeed proceed to the bitter end. However, it should stop gracefully instead of an error. I'll fix this.

Please confirm if your full model is overfitted (no residual variation). It it is not overfitted, there is some unknown problem and we need a reproducible example.

**Comment by eggxo** [comment]
thank u Sir!
