### ISSUE TITLE
Misleading summary in capscale (db-RDA)?

### ISSUE THREAD

**Issue by fvlampe** [vegandevs/vegan#636]
Dear devs,

I recently calculated db-RDA with capscale and realised one thing in the model outputs:

The reported results differ when calling the model object directly with `model ` and when calling `summary(model)`. When calling the model object negative Eigenvalues are reported as seperate item of sum of negative eigenvalues (_Imaginary_; as stated in the documentary). When calling `summary(model)` the item of sum of negative eigenvalues is entirely missing and all proportions are calculated only based on the axes with non-negative Eigenvalues. This may be very misleading, especially when one is only using `summary()` to call the full results?

Thanks for all and all the best,
Friedemann

Here an example output:

```
> species.dbrda    
Call: capscale(formula = species.log ~ AP + MAT + t_cover + twi_alos_posgar_10 +
   heat_load_alos_posgar_10 + Condition(transect), data = env, distance = "bray", sqrt.dist = F, add = F)

               Inertia Proportion Rank
Total         50.68149    1.00000     
Conditional    1.24226    0.02451    1
Constrained   13.43771    0.26514    5
Unconstrained 42.15945    0.83185   80
Imaginary     -6.15793   -0.12150   60
Inertia is squared Bray distance 
Species scores projected from ‘species.log’ 


> summary(species.dbrda)
Call:
capscale(formula = species.log ~ AP + MAT + t_cover + twi_alos_posgar_10 +      
  heat_load_alos_posgar_10 + Condition(transect), data = env,  distance = "bray", sqrt.dist = F, add = F) 

Partitioning of squared Bray distance:
              Inertia Proportion
Total          56.839    1.00000
Conditioned     1.242    0.02186
Constrained    13.438    0.23642
Unconstrained  42.159    0.74173

Eigenvalues, and their contribution to the squared Bray distance 
after removing the contribution of conditiniong variables
```

**Comment by jarioksa** [comment]
Please do not call `capscale` to db-RDA: we do have a function for db-RDA, and it is called `dbrda`. `capscale` is something related, but not the real thing.

I really do not know what is right and wrong in handling negative eigenvalues in `capscale`. You can see this scanning commit history of `capscale` where alternative ways have been alternating. It is clear that now we have two inconsistent ways of reporting negative eigenvalues. In old times we did not report negative eigenvalues at all, and their handling was fixed in release 1.17-6 (2011-01-10). In vegan 2.4-0 (2016-06-15) we introduced real `dbrda` and in this connection we also added reporting on negative eigenvalues in `capscale`. However, we did not notice that we should change the `summary` as well – mainly because nobody of us was using `summary` any longer  – and @gavinsimpson had promised to rewrite `summary` anyway (issue #203). We also discussed deprecating and ultimately removing `capscale` function (issue #217) in favour of `dbrda`, but I made a mistake and let it linger with minimal maintenance.

I'll make the `summary` consistent with the modern way.

**Comment by fvlampe** [comment]
Thanks a lot for taking care of this topic so quickly and for the detailed analysis and explanation!

I am not expert enough to have a clear opinion, but it seems to me that Option 2 is very unintuitive and explained proportions seem overestimated and not meaningful. 
Therefore consistent integration of Option 1 would allow to always recognize the presence of the imaginary component and get consistent proportions. Maybe even a note could be printed, indicating that the imaginary component is ignored in calculating the proportions. In that case, I guess the user should then go for Option 3 and apply one of the available corrections to avoid negative components at all.

I have remade my analysis with `dbrda` and don't see any reason to keep `capscale ` right now.

**Comment by jarioksa** [comment]
I think I have now changed most things to be consistent following option 1: ignore imaginary components and only base proportions on real components:
```
Call: capscale(formula = dune ~ Condition(Moisture) + Management, data
= dune.env, distance = "bray")

              Inertia Proportion Rank
Total          4.2990                
RealTotal      4.5939     1.0000     
Conditional    1.7440     0.3796    3
Constrained    0.9331     0.2031    3
Unconstrained  1.9169     0.4173   13
Imaginary     -0.2949                
Inertia is squared Bray distance 
```
The corresponding part in `summary` reads:
```
Partitioning of squared Bray distance:
              Inertia Proportion
Total          4.5939     1.0000
Conditioned    1.7440     0.3796
Constrained    0.9331     0.2031
Unconstrained  1.9169     0.4173
```
`RsquareAdj` was also changed to return:
```r
$r.squared
[1] 0.2031098

$adj.r.squared
[1] 0.133984
```
Many other functions changed on the way. See commit history if you want to see all changes. Some of these changes do not directly relate to these `capscale` changes, but things I found while inspecting this issue.

Some bigger associated changes are:
- `summary`  was made less verbose per wishes in issue #203.
-  `dbrda`:  `summary` of `eigenvals` shows now proportions of eigenvalues against sum of *all* eigenvalues, or the original inertia of the input dissimilarities. This means that proportions add up to >1 for positive eigenvalues and goes down to 1 with negative eigenvalues. Here I'm open to opinion. I haven't yet decided how to handle broken sticks of eigenvalues: now `bstick` refuses to touch `dbrda` because she doesn't know what is the total inertia.
