### ISSUE TITLE
Suggestion : Add functions for PCA and CA that just call `rda()` and `cca()` in the background

### ISSUE THREAD

**Issue by cmartin** [vegandevs/vegan#655]
Hi,

I'm teaching every year an undergrad course where we use vegan for many useful things (nmds, hclust,kmeans, etc.).

Since this is an undergrad course, we don't go into canonical ordinations, but I like my students to have a constant interface when doing multivariate analysis so we use vegan also for pca and ca, especially since vegan is THE multivariate library to know in ecology.

Every year though, I see the confusion in their eyes that they use a function named for another statistical method because it can do both.

Would it be possible to add both a pca and ca method that just call rda and cca transparently in the background?

Thanks you for your time and great package!

**Comment by jarioksa** [comment]
You mean these functions?
```r
ca <- function(x, ...) cca(x, ...)
pca <- function(x, scale = FALSE, ...) rda(x, scale = scale, ...)
```

**Comment by gavinsimpson** [comment]
@jarioksa Yes; I face the same questions every time I have to teach vegan to people. I know it's trivial to write those functions myself, but that doesn't help the students.

I was going to propose this in a PR but @cmartin has beaten me to the proposing.

But making this change gets my full support and I'll even do the PR if you are OK with it Jari?

**Comment by gavinsimpson** [comment]
I would also add `pco()` to the proposed list as a wrapper around `wcmdscale()`

**Comment by cmartin** [comment]
Yes @jarioksa , that's exactly what I meant.

Thanks @gavinsimpson for putting this in action.

I can't believe how fast you guys reacted! I should have posted this suggestion YEARS ago LOL

**Comment by jarioksa** [comment]
OK Gav, just go on!. Anyway it's a bit more complicated than my suggestion above: you need to adjust the call as well. There may be other bits where you need changes for support functions. For pco you probably mean making `eig=TRUE` default?

**Comment by gavinsimpson** [comment]
@jarioksa Will do (and yes, I realize the actual functions will need some messing with the call - things are never that simple :-)

For `pco()`, yes, I think so. At least that's how I was calling `wcmdscale()` when I wrote my slide on it but I don't use it except when I have to teach, so I need to refresh my memory on it.

**Comment by jarioksa** [comment]
See issue #186 which suggests having eigenvalues etc for default `wcmdscale`. Then I declined, because `wcmdscale` was designes as a drop-in replacement of `stats::cmdscale`, but `pco()` could solve this anomaly.

**Comment by jarioksa** [comment]
Another option is to make `pco` as a wrapper to `dbrda` (which only has formula interface currently).

Please note that it would be possible to call directly `ordConstrained` set of functions:
```r
ca <- function(x, ....) ordConstrained(x, method="cca", ...)
pca <- function(x, scale = FALSE, ...) ordConstrained(x, method="rda", scale = arg, ...)
pco <- function(d, ...) ordConstrained(d, method = "dbrda", ...)
```
This will set header info and names as well (`ordHead`), and if you want to omit those, there are only essential analytic steps: `init*` and `ordResid`. For instance:
```r
pco <- function(d, ...)
{
    d <- initDBRDA(d)
    ordResid(d)
}
```
This will only return numeric result without janitorial stuff of `dbrda`.

**Comment by jarioksa** [comment]
@gavinsimpson I think it is best to implement `pco()` as a wrapper to `dbrda`  so that all these functions (`pca`, `ca`, `pco`) have similar output, support functions and user  experience. You can also have Cailliez & Lingoes distortions with `dbrda` (but not with direct call to `ordConstrained(..., method = "dbrda", ...)`). The prototype would be:
```r
pco <- function(d, ...) dbrda(d ~ 1, ...)
```

**Comment by gavinsimpson** [comment]
These are now implemented in the GitHub (development version).

@jarioksa, should these be cherry-picked to 2.6-6.2 so that they will be more immediately avaiable?

**Comment by jarioksa** [comment]
@gavinsimpson yes indeed, I think that these should be cherry-picked `-x` (use this switch) to cran-2.6-6 branch. Now I think that we should release 2.6-6.2 in mid-August before the (northern hemisphere) university teaching season (which seems to be called 'semester' in the English world, while 'semester' in Scandinavia means holiday). The fix is a (relatively) save wrapped and intended for teaching purposes, and we should have it in teaching release.

Please note that cran-2.6-6 has not moved `inst/NEWS.md` to the main directory. I did not see a need for this because there is no github.io page for the 2.6-6 branch. Currently the NEWS live in parallel universe live in parallel universes: master lives like there will be no new CRAN releases, and cran-2.6-6 like there will be. After release the NEWS need synchronizing, but now they are separate.

**Comment by gavinsimpson** [comment]
@jarioksa Done; I think a mid-August release would be good

**Comment by gavinsimpson** [comment]
A minor thing here @jarioksa, but as I was writing to Dave Roberts about this change and how it might impact labdsv users, I realise we can avoid the `scores()` issue if we just use a different class on objects returned by `pca()` and `pco()` (and perhaps `ca()` just to end run any problems we/users haven't encountered yet but are out there lurking).

Right now I'm thinking of using

* `"vegan_pca"`,
* `"vegan_pco"`, and
* `"vegan_ca"`

which is silly but won't clash with anything.

(None of this will change anything in vegan because these objects inherit from `"cca"` ultimately and the correct methods will be used. But it will save us some grief from users encountering problems if they have both labdsv and vegan loaded.)

Thoughts, objections?

**Comment by jarioksa** [comment]
Perhaps silly, but ingenious: go for it. It is a good thing if it fixes realized and potential problems.

**Comment by gavinsimpson** [comment]
OK; that's done. This is good to go.

**Comment by jarioksa** [comment]
I've been toying with idea of changing the constrained ordination base class from `cca` to `rda`:

method | inheritance now | alternative inheritance
--------|-----------------|-----------------------
**cca** | `cca`| `cca`, `rda`
**rda** | `rda`, `cca`| `rda`
**capscale** | `capscale`, `rda`, `cca`| `capscale`, `rda`
**dbrda** | `dbrda`, `rda`, `cca`| `dbrda`, `rda`

and `pca`, `ca`& `pco` add their class as the first one to these.

**Reason to change inheritance**: make the inheritance chains shorter and more logical. Strictly no distance-based method inherits from `cca`, but they do inherit from `rda`, and `cca` can also be seen as a derived method of `rda`.

**Reasons not to change inheritance** is the mess and destruction this will bring along. Just look at this:
```r
> methods(class="cca")
 [1] add1           alias          anova          as.mlm         biplot        
 [6] bstick         calibrate      coef           cooks.distance deviance      
[11] df.residual    drop1          eigenvals      extractAIC     fitted        
[16] goodness       hatvalues      labels         model.frame    model.matrix  
[21] nobs           permutest      plot           points         predict       
[26] print          qr             residuals      RsquareAdj     rstandard     
[31] rstudent       scores         screeplot      sigma          simulate      
[36] SSD            stressplot     summary        text           tolerance     
[41] vcov           weights       
> methods(class="rda")
 [1] biplot       coef         deviance     fitted       hatvalues   
 [6] model.matrix plot         predict      print        RsquareAdj  
[11] scores       simulate     stressplot   weights     
> methods(class="dbrda")
[1] fitted      predict     simulate    sppscores<- stressplot 
> methods(class="capscale")
[1] fitted      simulate    sppscores<- stressplot 
``` 
Even more mess is expected from all `if (inherits(x, "cca"))`, `if(inherits(x, "rda"))` cases within these *and* other functions. These all should be re-considered if the base class changes. Is it worth it all?

**Why is cca the base class?** History: `cca` was published in **vegan** nearly one year earlier than `rda`. My intention was only to have `cca` and never `rda`, because CCA is uniformly better method than RDA: in the worst case it is as bad as RDA, but usually it is better. Then came these metric guys stuck to Euclid and I yielded to the public pressure and added `rda` – it was easier to do than always explain that it should not be used.

**Comment by gavinsimpson** [comment]
@jarioksa thanks for cherrypicking the latest class change onto the cran branch

**Comment by gavinsimpson** [comment]
@jarioksa hmm, while I think it would be nicer to have the classes represent better the inheritance, I doubt it is worth the developer effort for something that will largely be transparent to the vast majority of users.

If you can see a tangible benefit to this then go for it, but the inheritance doesn't have to reflect how the math methods build off one another but rather how code methods relate.
