### ISSUE TITLE
Incorrect number of neighbors when plotting isomap

### ISSUE THREAD

**Issue by simon-m** [vegandevs/vegan#95]
When ploting an isomap object, I observed that some points have more neighbors than expected. I have check that it was not due to overlapping points.

Minimal working example:
```R
library(vegan)
set.seed(15)
dataset <- data.frame(matrix(rnorm(1000), ncol=8))
imap <- isomap(dist(dataset), k=4)
plot(imap)
which(imap$points[,2] > 4) # check for overlap
 ```
The top point has five neighbors whereas k was set to 4.

**Comment by jarioksa** [comment]
This may be surprising, but it is documented in `?isomap`:

Function `isomapdist` retains either dissimilarities equal or
shorter to `epsilon`, or if `epsilon` is not given, **at least** `k`
shortest dissimilarities for a point.

This seems to have the case: there are no fewer than four neighbours.

**Comment by gavinsimpson** [comment]
I don't believe that the definition of `k` that is used in `?isomap`

```
       k: Number of shortest dissimilarities retained for a point. If
          both ‘epsilon’ and ‘k’ are given, ‘epsilon’ will be used.
```

pertains to `k` being the number of neighbours as indicated by the grey line segments on the plot.

All that is being done here is to retain the `k` closest points to each point. That doesn't mean that a point will only be joined to `k` other points. Consider a point that is towards the centre of a cloud of points and `k = 2`. It is easy to see that the central point could be one of the two shortest distances to several or indeed all of the points around it and hence it would have many more than `k = 2` connections.

This is easier to see with a smaller data set, for example:

```r
set.seed(15)
dataset <- data.frame(matrix(rnorm(12 * 8), ncol=8))
imap <- isomap(dist(dataset), k=2)
plot(imap)
```

The code is doing what it claims to do. The key line is (from `isomapdist()`):

```r
is.na(dist) <- apply(dist, 2, function(x) x > x[order(x, na.last = TRUE)[k]])
```

where the anonymous function is sorting the dissimilarities for a given site/sample, in *increasing order* and selecting the `k`th dissimilarity against which to select points with dissimilarity greater than this (it is selecting the ones greater than the `k`th dissimilarity because we wish to turn them to `NA`, i.e. get rid of those dissimilarities). In all the examples I tried, this only ever would leave 4 (when `k = 4`) untouched. That is not guaranteed however; if there were several points at exactly the same distance from the target point we could end up retaining more than `k`. But it is important to note that this is what the function/method is supposed to do.

**Comment by jarioksa** [comment]
I expand the argument a bit. The following two conditions cannot be simultaneously true:

1. Four nearest points are connected to the focal point.
2. Each point is connected exactly to four other points.

Assume you have point **A** that already is connected to four of its closest points. Take  point **B** further away that has that point **A** as its closest point. If you connect **A** to **B**, then **A** will either have five neighbours, or if you retain the connection to **B** you will have to drop some of the closer neighbours. You just cannot have both.

Moreover, it is very common that the number of dissimilarities is not a multiple of *k*.

**Comment by jarioksa** [comment]
This is a closed issue, but perhaps I still elaborate a bit, and perhaps something of this should be written in the documentation (`man/isomap.Rd`).

The key problem is that nearest neighbour is a non-symmetric relationship: **B**  can be the nearest neighbour of **A**, but **A** may not be the nearest neighbour of **B**. In the following, arrow points from the nearest neighbour to the focal point:

**A**<-------**B**<-->**C**

Reading **B** is nearest neighbour to **A**, **C** is nearest neighbour to **B** and **B** is the nearest neighbour to **C**.  We had a *k*=1 net, but **B** was connected by a line to two other points. However, only *k* arrows are pointing to each point, and this actually is the meaning of *k*.
